[package]
name = "rustybar"
version = "0.2.0"
edition = "2024"

[dependencies]
async-stream = "0.3.6"
async-trait = "0.1.92"
base64 = "0.23.1"
color-eyre = "0.6.5"
config = "0.15.25"
directories = "6.0.0"
eyre = "0.6.14"
futures = "0.3.34"
iced = { version = "0.14.0", features = ["advanced", "canvas", "image", "svg", "tokio"] }
iced_core = { version = "0.14.0", features = ["serde"] }
iced_layershell = "0.19.1"
inotify = "0.11.5"
jiff = "0.2.37"
niri-ipc = "26.4.0"
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
starship-battery = "0.11.1"
strum = { version = "0.28.0", features = ["derive"] }
sysinfo = "0.39.6"
system-tray = "0.8.9"
tokio = { version = "1.53.1", features = ["full"] }
typetag = "0.2"
zbus = { version = "5", default-features = false, features = ["tokio"] }
