# --- global parameters ------
font = "Monospace"
fontsize = 9
left_gap = 10
right_gap = 50
height = 18
background = "#000000"

# --- left section -----------
[[left]]
  space = 1

# --- center section ---------
[[center]]
  space = 3
[[center]]
  [center.cpu]
    width = 20
    height = 10
    space = 8
[[center]]
  space = 3

# --- right section ----------
[[right]]
  space = -1
[[right]]
  [right.brightness]
    width = 30
    height = 10
[[right]]
  space = -1
[[right]]
  [right.volume]
    width = 30
    height = 10
    card = 1
    channel = "Master"
[[right]]
  space = 20
[[right]]
  [right.battery]
    width = 30
    height = 10
    space = 8
    battery_numer = 0
[[right]]
  space = -1
